<h1>Projects</h1>
<a href="<?php echo $this->addUrl; ?>">Nouveau projet</a>
<?php if ($this->elements->count() == 0) : ?>
    <p>Aucun projet en cours</p>
<?php else: ?>
    <?php foreach ($this->elements as $project) : ?>
        <div class="project">
            <h4><?php echo $project->name; ?></h4>
        </div>
    <?php endforeach; ?>
    <table class="crud">
        <tr>
            <?php foreach ($this->columns as $column) : ?>
                <th><?php echo $column; ?></th>
            <?php endforeach; ?>
        </tr>
        <?php foreach ($this->elements as $element) : ?>
            <tr>
                <?php foreach ($element as $value) : ?>
                    <td><?php echo $value; ?></td>
                <?php endforeach; ?>
                <td class="action">
                    <a href="<?php printf($this->editUrl, $element->{$this->primaryKey}); ?>">Modifier</a>
                </td>
                <td class="action">
                    <a href="<?php printf($this->deleteUrl, $element->{$this->primaryKey}); ?>">Supprimer</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>

