<h1>Tâches</h1>
<a href="<?php echo $this->addUrl; ?>" class="popup">Ajouter</a>
<?php if ($this->elements->count() == 0) : ?>
    <p>Aucune tâche effectuée</p>
<?php else: ?>
    <table class="crud">
        <tr>
            <?php foreach ($this->columns as $column) : ?>
                <th><?php echo $column; ?></th>
            <?php endforeach; ?>
        </tr>
        <?php foreach ($this->elements as $element) : ?>
            <tr>
                <?php foreach ($element as $key => $value) : ?>
                    <?php if (isset($this->columns[$key])) : ?>
                    <td>
                        <?php echo $value; ?>
                    </td>
                    <?php endif; ?>
                <?php endforeach; ?>
                <td class="action">
                    <a href="<?php printf($this->editUrl, $element->{$this->primaryKey}); ?>" class="popup">Modifier</a>
                </td>
                <td class="action">
                    <a href="<?php printf($this->deleteUrl, $element->{$this->primaryKey}); ?>">Supprimer</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
