<h1>Utilisateurs</h1>
<a href="<?php echo $this->addUrl; ?>">Ajouter</a>
<?php if ($this->elements->count() == 0) : ?>
    <p>Aucun utilisateur</p>
<?php else: ?>
    <table class="crud">
        <tr>
            <?php foreach ($this->columns as $column) : ?>
                <th><?php echo $column; ?></th>
            <?php endforeach; ?>
        </tr>
        <?php foreach ($this->elements as $element) : ?>
            <tr>
                <?php foreach ($element as $value) : ?>
                    <td><?php echo $value; ?></td>
                <?php endforeach; ?>
                <td class="action">
                    <a href="<?php printf($this->editUrl, $element->{$this->primaryKey}); ?>">Modifier</a>
                </td>
                <td class="action">
                    <a href="<?php printf($this->deleteUrl, $element->{$this->primaryKey}); ?>">Supprimer</a>
                </td>
                <td class="action">
                    <?php if ($element->active == 1) : ?>
                    <a href="/user/disable/userId/<?php echo $element->userId ?>">Désactiver</a>
                    <?php else : ?>
                    <a href="/user/active/userId/<?php echo $element->userId ?>">Activer</a>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
    <div class="pagination"><?php echo $this->nbElements; ?> users</div>
<?php endif; ?>
